/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ProductCategory = IDL.Variant({
  'ring' : IDL.Null,
  'diamond' : IDL.Null,
  'bracelet' : IDL.Null,
  'headpiece' : IDL.Null,
});
export const Material = IDL.Variant({
  '_18K_gold' : IDL.Null,
  '_9K_gold' : IDL.Null,
  '_22K_gold' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductId = IDL.Nat;
export const Principal = IDL.Principal;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderId = IDL.Nat;
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'stock' : IDL.Nat,
  'category' : ProductCategory,
  'price' : IDL.Nat,
  'material' : Material,
  'images' : IDL.Vec(ExternalBlob),
});
export const DownloadId = IDL.Nat;
export const Download = IDL.Record({
  'id' : DownloadId,
  'platform' : IDL.Text,
  'device' : IDL.Text,
  'version' : IDL.Text,
  'timestamp' : IDL.Int,
  'browser' : IDL.Text,
  'sessionId' : IDL.Text,
  'location' : IDL.Text,
});
export const CustomerProfile = IDL.Record({
  'id' : Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'delivered' : IDL.Null,
});
export const CustomerId = IDL.Principal;
export const OrderItem = IDL.Record({
  'productId' : ProductId,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Nat,
  'customerId' : CustomerId,
  'items' : IDL.Vec(OrderItem),
});
export const OrderWithCustomerDetails = IDL.Record({
  'customer' : CustomerProfile,
  'order' : Order,
  'lastStatusUpdate' : IDL.Int,
  'isNew' : IDL.Bool,
});
export const VisitId = IDL.Nat;
export const Visit = IDL.Record({
  'id' : VisitId,
  'page' : IDL.Text,
  'device' : IDL.Text,
  'timestamp' : IDL.Int,
  'browser' : IDL.Text,
  'sessionId' : IDL.Text,
  'location' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const CartItem = IDL.Record({
  'productId' : IDL.Nat,
  'quantity' : IDL.Nat,
});
export const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
export const BusinessContactInfo = IDL.Record({
  'bankAccount' : IDL.Text,
  'ifscCode' : IDL.Text,
  'storeAddress' : IDL.Text,
  'gstNumber' : IDL.Text,
  'description' : IDL.Text,
  'email' : IDL.Text,
  'storeName' : IDL.Text,
  'phone' : IDL.Text,
});
export const Logo = IDL.Record({
  'id' : IDL.Nat,
  'uploadTimestamp' : IDL.Int,
  'version' : IDL.Nat,
  'image' : ExternalBlob,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const InventoryUpdate = IDL.Record({
  'productId' : ProductId,
  'stock' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        ProductCategory,
        Material,
        IDL.Nat,
        IDL.Vec(ExternalBlob),
      ],
      [ProductId],
      [],
    ),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
  'assignAdminWithEmail' : IDL.Func([Principal, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'cancelOrder' : IDL.Func([OrderId], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'filterProductsByCategory' : IDL.Func(
      [ProductCategory],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'filterProductsByMaterial' : IDL.Func(
      [Material],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'filterProductsByPriceRange' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'getAllDownloads' : IDL.Func([], [IDL.Vec(Download)], ['query']),
  'getAllOrdersWithCustomerDetails' : IDL.Func(
      [],
      [IDL.Vec(OrderWithCustomerDetails)],
      ['query'],
    ),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllVisits' : IDL.Func([], [IDL.Vec(Visit)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [Cart], ['query']),
  'getContactInfo' : IDL.Func([], [BusinessContactInfo], ['query']),
  'getCurrentLogo' : IDL.Func([], [IDL.Opt(Logo)], ['query']),
  'getCurrentSystemTime' : IDL.Func([], [IDL.Int], ['query']),
  'getCustomerOrders' : IDL.Func([CustomerId], [IDL.Vec(Order)], ['query']),
  'getCustomerProfile' : IDL.Func([CustomerId], [CustomerProfile], ['query']),
  'getDownloadCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getFilteredDownloads' : IDL.Func([IDL.Text], [IDL.Vec(Download)], ['query']),
  'getFilteredVisits' : IDL.Func([IDL.Text], [IDL.Vec(Visit)], ['query']),
  'getNewAndUpdatedOrders' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(OrderWithCustomerDetails)],
      ['query'],
    ),
  'getNewAndUpdatedOrdersWithCustomerDetails' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(OrderWithCustomerDetails)],
      ['query'],
    ),
  'getOrder' : IDL.Func([OrderId], [Order], ['query']),
  'getOrderWithCustomerDetails' : IDL.Func(
      [OrderId],
      [OrderWithCustomerDetails],
      ['query'],
    ),
  'getOrdersForPolling' : IDL.Func(
      [],
      [IDL.Vec(OrderWithCustomerDetails)],
      ['query'],
    ),
  'getPendingOrdersWithCustomerDetails' : IDL.Func(
      [],
      [IDL.Vec(OrderWithCustomerDetails)],
      ['query'],
    ),
  'getProduct' : IDL.Func([ProductId], [Product], ['query']),
  'getProductsBySearch' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'getRecentOrdersForPolling' : IDL.Func(
      [IDL.Int],
      [IDL.Vec(OrderWithCustomerDetails)],
      ['query'],
    ),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
  'getVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
  'isAdminEmailLookup' : IDL.Func([Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([], [OrderId], []),
  'recordDownload' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'recordVisit' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'registerCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'removeFromCart' : IDL.Func([ProductId], [], []),
  'revertToPreviousLogo' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateContactInfo' : IDL.Func([BusinessContactInfo], [], []),
  'updateCurrentLogo' : IDL.Func([ExternalBlob], [], []),
  'updateCustomerProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateInventory' : IDL.Func([IDL.Vec(InventoryUpdate)], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateProduct' : IDL.Func(
      [
        ProductId,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        ProductCategory,
        Material,
        IDL.Nat,
        IDL.Vec(ExternalBlob),
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ProductCategory = IDL.Variant({
    'ring' : IDL.Null,
    'diamond' : IDL.Null,
    'bracelet' : IDL.Null,
    'headpiece' : IDL.Null,
  });
  const Material = IDL.Variant({
    '_18K_gold' : IDL.Null,
    '_9K_gold' : IDL.Null,
    '_22K_gold' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductId = IDL.Nat;
  const Principal = IDL.Principal;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderId = IDL.Nat;
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'stock' : IDL.Nat,
    'category' : ProductCategory,
    'price' : IDL.Nat,
    'material' : Material,
    'images' : IDL.Vec(ExternalBlob),
  });
  const DownloadId = IDL.Nat;
  const Download = IDL.Record({
    'id' : DownloadId,
    'platform' : IDL.Text,
    'device' : IDL.Text,
    'version' : IDL.Text,
    'timestamp' : IDL.Int,
    'browser' : IDL.Text,
    'sessionId' : IDL.Text,
    'location' : IDL.Text,
  });
  const CustomerProfile = IDL.Record({
    'id' : Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'delivered' : IDL.Null,
  });
  const CustomerId = IDL.Principal;
  const OrderItem = IDL.Record({
    'productId' : ProductId,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Nat,
    'customerId' : CustomerId,
    'items' : IDL.Vec(OrderItem),
  });
  const OrderWithCustomerDetails = IDL.Record({
    'customer' : CustomerProfile,
    'order' : Order,
    'lastStatusUpdate' : IDL.Int,
    'isNew' : IDL.Bool,
  });
  const VisitId = IDL.Nat;
  const Visit = IDL.Record({
    'id' : VisitId,
    'page' : IDL.Text,
    'device' : IDL.Text,
    'timestamp' : IDL.Int,
    'browser' : IDL.Text,
    'sessionId' : IDL.Text,
    'location' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const CartItem = IDL.Record({ 'productId' : IDL.Nat, 'quantity' : IDL.Nat });
  const Cart = IDL.Record({ 'items' : IDL.Vec(CartItem) });
  const BusinessContactInfo = IDL.Record({
    'bankAccount' : IDL.Text,
    'ifscCode' : IDL.Text,
    'storeAddress' : IDL.Text,
    'gstNumber' : IDL.Text,
    'description' : IDL.Text,
    'email' : IDL.Text,
    'storeName' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Logo = IDL.Record({
    'id' : IDL.Nat,
    'uploadTimestamp' : IDL.Int,
    'version' : IDL.Nat,
    'image' : ExternalBlob,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const InventoryUpdate = IDL.Record({
    'productId' : ProductId,
    'stock' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          ProductCategory,
          Material,
          IDL.Nat,
          IDL.Vec(ExternalBlob),
        ],
        [ProductId],
        [],
      ),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [], []),
    'assignAdminWithEmail' : IDL.Func([Principal, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'cancelOrder' : IDL.Func([OrderId], [], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'filterProductsByCategory' : IDL.Func(
        [ProductCategory],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'filterProductsByMaterial' : IDL.Func(
        [Material],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'filterProductsByPriceRange' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getAllDownloads' : IDL.Func([], [IDL.Vec(Download)], ['query']),
    'getAllOrdersWithCustomerDetails' : IDL.Func(
        [],
        [IDL.Vec(OrderWithCustomerDetails)],
        ['query'],
      ),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllVisits' : IDL.Func([], [IDL.Vec(Visit)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [Cart], ['query']),
    'getContactInfo' : IDL.Func([], [BusinessContactInfo], ['query']),
    'getCurrentLogo' : IDL.Func([], [IDL.Opt(Logo)], ['query']),
    'getCurrentSystemTime' : IDL.Func([], [IDL.Int], ['query']),
    'getCustomerOrders' : IDL.Func([CustomerId], [IDL.Vec(Order)], ['query']),
    'getCustomerProfile' : IDL.Func([CustomerId], [CustomerProfile], ['query']),
    'getDownloadCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getFilteredDownloads' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Download)],
        ['query'],
      ),
    'getFilteredVisits' : IDL.Func([IDL.Text], [IDL.Vec(Visit)], ['query']),
    'getNewAndUpdatedOrders' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(OrderWithCustomerDetails)],
        ['query'],
      ),
    'getNewAndUpdatedOrdersWithCustomerDetails' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(OrderWithCustomerDetails)],
        ['query'],
      ),
    'getOrder' : IDL.Func([OrderId], [Order], ['query']),
    'getOrderWithCustomerDetails' : IDL.Func(
        [OrderId],
        [OrderWithCustomerDetails],
        ['query'],
      ),
    'getOrdersForPolling' : IDL.Func(
        [],
        [IDL.Vec(OrderWithCustomerDetails)],
        ['query'],
      ),
    'getPendingOrdersWithCustomerDetails' : IDL.Func(
        [],
        [IDL.Vec(OrderWithCustomerDetails)],
        ['query'],
      ),
    'getProduct' : IDL.Func([ProductId], [Product], ['query']),
    'getProductsBySearch' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
    'getRecentOrdersForPolling' : IDL.Func(
        [IDL.Int],
        [IDL.Vec(OrderWithCustomerDetails)],
        ['query'],
      ),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func([Principal], [IDL.Opt(UserProfile)], ['query']),
    'getVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
    'isAdminEmailLookup' : IDL.Func([Principal], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([], [OrderId], []),
    'recordDownload' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'recordVisit' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'registerCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'removeFromCart' : IDL.Func([ProductId], [], []),
    'revertToPreviousLogo' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateContactInfo' : IDL.Func([BusinessContactInfo], [], []),
    'updateCurrentLogo' : IDL.Func([ExternalBlob], [], []),
    'updateCustomerProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateInventory' : IDL.Func([IDL.Vec(InventoryUpdate)], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateProduct' : IDL.Func(
        [
          ProductId,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          ProductCategory,
          Material,
          IDL.Nat,
          IDL.Vec(ExternalBlob),
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };