/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BusinessContactInfo {
  'bankAccount' : string,
  'ifscCode' : string,
  'storeAddress' : string,
  'gstNumber' : string,
  'description' : string,
  'email' : string,
  'storeName' : string,
  'phone' : string,
}
export interface Cart { 'items' : Array<CartItem> }
export interface CartItem { 'productId' : bigint, 'quantity' : bigint }
export type CustomerId = Principal;
export interface CustomerProfile {
  'id' : Principal,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface Download {
  'id' : DownloadId,
  'platform' : string,
  'device' : string,
  'version' : string,
  'timestamp' : bigint,
  'browser' : string,
  'sessionId' : string,
  'location' : string,
}
export type DownloadId = bigint;
export type ExternalBlob = Uint8Array;
export interface InventoryUpdate { 'productId' : ProductId, 'stock' : bigint }
export interface Logo {
  'id' : bigint,
  'uploadTimestamp' : bigint,
  'version' : bigint,
  'image' : ExternalBlob,
}
export type Material = { '_18K_gold' : null } |
  { '_9K_gold' : null } |
  { '_22K_gold' : null };
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'createdAt' : bigint,
  'totalAmount' : bigint,
  'customerId' : CustomerId,
  'items' : Array<OrderItem>,
}
export type OrderId = bigint;
export interface OrderItem {
  'productId' : ProductId,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'delivered' : null };
export interface OrderWithCustomerDetails {
  'customer' : CustomerProfile,
  'order' : Order,
  'lastStatusUpdate' : bigint,
  'isNew' : boolean,
}
export type Principal = Principal;
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'stock' : bigint,
  'category' : ProductCategory,
  'price' : bigint,
  'material' : Material,
  'images' : Array<ExternalBlob>,
}
export type ProductCategory = { 'ring' : null } |
  { 'diamond' : null } |
  { 'bracelet' : null } |
  { 'headpiece' : null };
export type ProductId = bigint;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Visit {
  'id' : VisitId,
  'page' : string,
  'device' : string,
  'timestamp' : bigint,
  'browser' : string,
  'sessionId' : string,
  'location' : string,
}
export type VisitId = bigint;
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<
    [
      string,
      string,
      bigint,
      ProductCategory,
      Material,
      bigint,
      Array<ExternalBlob>,
    ],
    ProductId
  >,
  'addToCart' : ActorMethod<[ProductId, bigint], undefined>,
  'assignAdminWithEmail' : ActorMethod<[Principal, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'cancelOrder' : ActorMethod<[OrderId], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'filterProductsByCategory' : ActorMethod<[ProductCategory], Array<Product>>,
  'filterProductsByMaterial' : ActorMethod<[Material], Array<Product>>,
  'filterProductsByPriceRange' : ActorMethod<[bigint, bigint], Array<Product>>,
  'getAllDownloads' : ActorMethod<[], Array<Download>>,
  'getAllOrdersWithCustomerDetails' : ActorMethod<
    [],
    Array<OrderWithCustomerDetails>
  >,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllVisits' : ActorMethod<[], Array<Visit>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], Cart>,
  'getContactInfo' : ActorMethod<[], BusinessContactInfo>,
  'getCurrentLogo' : ActorMethod<[], [] | [Logo]>,
  'getCurrentSystemTime' : ActorMethod<[], bigint>,
  'getCustomerOrders' : ActorMethod<[CustomerId], Array<Order>>,
  'getCustomerProfile' : ActorMethod<[CustomerId], CustomerProfile>,
  'getDownloadCount' : ActorMethod<[], bigint>,
  'getFilteredDownloads' : ActorMethod<[string], Array<Download>>,
  'getFilteredVisits' : ActorMethod<[string], Array<Visit>>,
  'getNewAndUpdatedOrders' : ActorMethod<
    [bigint],
    Array<OrderWithCustomerDetails>
  >,
  'getNewAndUpdatedOrdersWithCustomerDetails' : ActorMethod<
    [bigint],
    Array<OrderWithCustomerDetails>
  >,
  'getOrder' : ActorMethod<[OrderId], Order>,
  'getOrderWithCustomerDetails' : ActorMethod<
    [OrderId],
    OrderWithCustomerDetails
  >,
  'getOrdersForPolling' : ActorMethod<[], Array<OrderWithCustomerDetails>>,
  'getPendingOrdersWithCustomerDetails' : ActorMethod<
    [],
    Array<OrderWithCustomerDetails>
  >,
  'getProduct' : ActorMethod<[ProductId], Product>,
  'getProductsBySearch' : ActorMethod<[string], Array<Product>>,
  'getRecentOrdersForPolling' : ActorMethod<
    [bigint],
    Array<OrderWithCustomerDetails>
  >,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVisitCount' : ActorMethod<[], bigint>,
  'isAdminEmailLookup' : ActorMethod<[Principal], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[], OrderId>,
  'recordDownload' : ActorMethod<
    [string, string, string, string, string, string],
    undefined
  >,
  'recordVisit' : ActorMethod<
    [string, string, string, string, string],
    undefined
  >,
  'registerCustomer' : ActorMethod<[string, string, string, string], undefined>,
  'removeFromCart' : ActorMethod<[ProductId], undefined>,
  'revertToPreviousLogo' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateContactInfo' : ActorMethod<[BusinessContactInfo], undefined>,
  'updateCurrentLogo' : ActorMethod<[ExternalBlob], undefined>,
  'updateCustomerProfile' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateInventory' : ActorMethod<[Array<InventoryUpdate>], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<
    [
      ProductId,
      string,
      string,
      bigint,
      ProductCategory,
      Material,
      bigint,
      Array<ExternalBlob>,
    ],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];